package main

import (
	"fmt"
	. "github.com/dave/jennifer/jen"
	"github.com/julien040/go-ternary"
	"os"
)

const (
	ctxKeyword = "ctx"
	reqKeyword = "req"
	resKeyword = "res"
)

func createControllerFile(data usefulData) error {
	jf := NewFile(data.modelServicePackageName)
	jf.ImportAlias("github.com/labstack/echo/v4", "echo")
	jf.PackageComment("Code generated by creatore")

	jf.Add(generateControllerCode(data))

	return jf.Render(os.Stdout)
}

func generateControllerCode(input usefulData) Code {
	return Null().
		Add(generateControllerStruct(input)).
		Line().
		Line().
		Add(generateControllerConstructor(input)).
		Line().
		Line().
		Add(routesRegistryMethod(input)).
		Line().
		Line().
		Add(generateControllerSaveMethod(input)).
		Line().
		Line().
		Add(generateControllerGetById(input)).
		Line().
		Line().
		Add(generateControllerGetAllPaginatedMethods(input)).
		Line().
		Line().
		Add(generateControllerUpdateSelectiveMethod(input)).
		Line().
		Line().
		Add(generateControllerDeleteByIdMethod(input))
}

func routesRegistryMethod(input usefulData) Code {
	groupVar := fmt.Sprintf("%sGroup", input.modelServicePackageName)
	baseRoute := fmt.Sprintf("/%s", input.modelServicePackageName)
	byIdRoute := fmt.Sprintf("%s/:id", baseRoute)

	return Func().
		Params(controllerReceiverParam(input)).
		Id("SetUpRoutes").
		Params(
			Id("group").Op("*").Qual("github.com/labstack/echo/v4", "Group"),
		).Block(
		Id(groupVar).
			Op(":=").
			Id("group").
			Dot("Group").
			Call(
				Lit(baseRoute),
			),
		Line(),
		Id(groupVar).Dot("GET").Call(Lit(baseRoute), Id(handlerMethodName(getAllPaginatedMethodKey))),
		Id(groupVar).Dot("POST").Call(Lit(baseRoute), Id(handlerMethodName(saveMethodKey))),
		Id(groupVar).Dot("GET").Call(Lit(byIdRoute), Id(handlerMethodName(getByIdMethodKey))),
		Id(groupVar).Dot("PATCH").Call(Lit(byIdRoute), Id(handlerMethodName(saveMethodKey))),
		Id(groupVar).Dot("PUT").Call(Lit(byIdRoute), Id(handlerMethodName(updateSelectiveByIdMethodKey))),
		Id(groupVar).Dot("DELETE").Call(Lit(byIdRoute), Id(handlerMethodName(deleteByIdMethodKey))),
	)
}

func generateControllerStruct(input usefulData) Code {
	return Null().
		Type().
		Id(input.controllerStructName).
		Struct(
			Id(input.repositoryStructVarName).Op("*").Qual(input.modelServicePackageName, input.repositoryStructName),
		)
}

func generateControllerConstructor(input usefulData) Code {
	return Func().
		Id(input.controllerStructConstructorName).
		Params(
			Id(input.repositoryStructVarName).Op("*").Qual(input.modelServicePackageName, input.repositoryStructName),
		).
		Op("*").Qual(input.modelServicePackageName, input.repositoryStructName).
		Block(
			Return(
				Op("&").Id(input.controllerStructName).Values(
					Dict{
						Id(input.repositoryStructVarName): Id(input.repositoryStructVarName),
					},
				),
			),
		)
}

func generateControllerSaveMethod(input usefulData) Code {
	return Func().
		Params(
			controllerReceiverParam(input),
		).
		Id(handlerMethodName(saveMethodKey)).
		Params(
			echoContextParam(),
		).
		Params(
			Error(),
		).
		Block(
			Var().Id(reqKeyword).Op("=").Add(input.modelStructQualifier).Values(),
			If(
				Err().Op(":=").Id("ctx").Dot("Bind").Call(
					Op("&").Id(reqKeyword),
				),
				Err().Op("!=").Nil(),
			).
				Block(
					Return(Err()),
				).Line(),
			If(
				Err().Op(":=").Id(ctxKeyword).Dot("Validate").Call(
					Op("&").Id(reqKeyword),
				),
				Err().Op("!=").Nil(),
			).
				Block(
					Return(Err()),
				).Line(),
			If(
				Err().Op(":=").Id(input.receiverVarName).Dot(input.repositoryStructVarName).Dot(saveMethodKey).Call(
					Op("&").Id(reqKeyword),
				),
				Err().Op("!=").Nil(),
			).Block(
				Return(Err()),
			),
			Return(
				Id(ctxKeyword).Dot("JSON").Call(Qual(netHttpQual, "StatusCreated"), Op("&").Id(reqKeyword)),
			),
		)
}

func generateControllerGetById(input usefulData) Code {
	var (
		methodName      = fmt.Sprintf("Get%sById", input.modelStructName)
		inputStructName = fmt.Sprintf("%sInput", methodName)
	)

	return Type().
		Id(inputStructName).
		Struct(
			Id("Id").
				Add(input.idTypeAsJenCode).
				Tag(map[string]string{
					"param":    "id",
					"json":     "id",
					"validate": "required required_uuid",
				}),
		).
		Line().
		Line().
		Func().
		Params(
			controllerReceiverParam(input),
		).
		Id(handlerMethodName(methodName)).
		Params(echoContextParam()).
		Error().
		Block(
			Id(reqKeyword).Op(":=").Id(inputStructName).Values(),
			If(
				Err().Op(":=").Id("ctx").Dot("Bind").Call(Op("&").Id(reqKeyword)),
				Err().Op("!=").Nil(),
			).
				Block(
					Return(
						Err(),
					),
				),
			If(
				Err().Op(":=").Id(ctxKeyword).Dot("Validate").Call(Op("&").Id(reqKeyword)),
				Err().Op("!=").Nil(),
			).Block(
				Return(Err()),
			),
			Line(),
			List(Id(resKeyword), Err()).Op(":=").Id(input.receiverVarName).Dot(input.repositoryStructVarName).Dot(getByIdMethodKey).Call(
				Id(reqKeyword).Dot("Id"),
			),
			If(Err().Op("!=").Nil()).Block(
				Return(Err()),
			),
			Line(),
			Return(
				Id(ctxKeyword).Dot("JSON").Call(Qual(netHttpQual, "StatusOK"), Op("&").Id(resKeyword)),
			),
		)
}

func generateControllerGetAllPaginatedMethods(input usefulData) Code {
	return Func().
		Params(controllerReceiverParam(input)).
		Id(handlerMethodName(getAllPaginatedMethodKey)).
		Params(echoContextParam()).
		Error().
		Block(
			Id(reqKeyword).Op(":=").Qual(winterCommonReqQual, winterRequestsPageData).Values(),
			If(
				Err().Op(":=").Qual(winterQual, winterBindAndValidate).Call(Id(ctxKeyword), Op("&").Id(reqKeyword)),
				Err().Op("!=").Nil(),
			).Block(
				Return(Err()),
			),
			Line(),
			List(Id(resKeyword), Err()).Op(":=").Id(input.receiverVarName).Dot(input.repositoryStructVarName).Dot(getAllPaginatedMethodKey).Call(
				Id(reqKeyword).Dot("PageNumber"), Id(reqKeyword).Dot("PageSize"),
			),
			If(Err().Op("!=").Nil()).Block(
				Return(Err()),
			),
			Line(),
			Return(
				Id(ctxKeyword).Dot("JSON").Call(
					Qual(netHttpQual, "StatusOK"),
					Op("&").Id(resKeyword),
				),
			),
		)
}

func generateControllerUpdateSelectiveMethod(input usefulData) Code {
	return Func().
		Params(controllerReceiverParam(input)).
		Id(handlerMethodName(updateSelectiveByIdMethodKey)).
		Params(echoContextParam()).
		Error().
		Block(
			Id(reqKeyword).Op(":=").Qual(input.modelServicePackageName, input.updateSelectiveByIdInputStructName).Values(),
			If(
				Err().Op(":=").Qual(winterQual, winterBindAndValidate).Call(Id(ctxKeyword), Op("&").Id(reqKeyword)),
				Err().Op("!=").Nil(),
			).Block(
				Return(Err()),
			),
			List(Id(resKeyword), Err()).Op(":=").Id(input.receiverVarName).Dot(input.repositoryStructVarName).Dot(updateSelectiveByIdMethodKey).Call(Id(reqKeyword)),
			If(Err().Op("!=").Nil()).Block(
				Return(Err()),
			),
			Line(),
			Return(
				Id(ctxKeyword).Dot("JSON").Call(
					Qual(netHttpQual, "StatusOK"),
					Op("&").Id(resKeyword),
				),
			),
		)
}

func generateControllerDeleteByIdMethod(input usefulData) Code {
	return Func().
		Params(controllerReceiverParam(input)).
		Id(handlerMethodName(deleteByIdMethodKey)).
		Params(echoContextParam()).
		Error().
		Block(
			Id(reqKeyword).Op(":=").Qual(winterCommonReqQual, ternary.If(input.isIdUUID, "GetByIdUUID", "GetById")).Values(),
			If(
				Err().Op(":=").Qual(winterQual, winterBindAndValidate).Call(Id(ctxKeyword), Op("&").Id(reqKeyword)),
				Err().Op("!=").Nil(),
			).Block(
				Return(Err()),
			),
			If(
				Err().Op(":=").Id(ctxKeyword).Dot(input.repositoryStructVarName).Dot(deleteByIdMethodKey).Call(
					Id(reqKeyword).Dot("Id"),
				),
				Err().Op("!=").Nil(),
			).Block(
				Return(Err()),
			),
			Return(
				Id(ctxKeyword).Dot("NoContent").Call(
					Qual(netHttpQual, "StatusOK"),
				),
			),
		)
}

func handlerMethodName(name string) string {
	return fmt.Sprintf("%sHandler", name)
}

func echoContextParam() Code {
	return Id(ctxKeyword).Qual("github.com/labstack/echo/v4", "Context")
}

func controllerReceiverParam(input usefulData) Code {
	return Id(input.receiverVarName).Op("*").Id(input.controllerStructName)
}
