package main

import (
	"fmt"
	"github.com/charmbracelet/log"
	. "github.com/dave/jennifer/jen"
	"github.com/julien040/go-ternary"
)

const (
	ctxKeyword = "ctx"
	reqKeyword = "req"
	resKeyword = "res"
)

func createControllerFile(data usefulData) error {
	log.Info("Creating controller code...")
	jf := NewFile(data.modelServicePackageName)
	jf.ImportAlias(echoQual, "echo")
	jf.PackageComment("Code generated by creatore")

	jf.Add(generateControllerCode(data))

	//if err := jf.Render(os.Stdout); err != nil {
	//	logger.Error(err.Error())
	//}

	return jf.Save(data.dirNames.controllerFile)
}

func generateControllerCode(input usefulData) Code {
	return Null().
		Add(generateControllerStruct(input)).
		Line().
		Line().
		Add(generateControllerConstructor(input)).
		Line().
		Line().
		Add(routesRegistryMethod(input)).
		Line().
		Line().
		Add(generateControllerSaveMethod(input)).
		Line().
		Line().
		Add(generateControllerGetById(input)).
		Line().
		Line().
		Add(generateControllerGetAllPaginatedMethods(input)).
		Line().
		Line().
		Add(generateControllerUpdateSelectiveMethod(input)).
		Line().
		Line().
		Add(generateControllerDeleteByIdMethod(input))
}

func routesRegistryMethod(input usefulData) Code {
	groupVar := fmt.Sprintf("%sGroup", input.modelServicePackageName)
	baseRoute := ""
	byIdRoute := "/:id"

	return Func().
		Params(controllerReceiverParam(input)).
		Id("SetUpRoutes").
		Params(
			Id("group").Op(pointerKeyword).Qual(echoQual, "Group"),
		).Block(
		Id(groupVar).
			Op(":=").
			Id("group").
			Dot("Group").
			Call(
				Lit(fmt.Sprintf("/%s", input.modelServicePackageName)),
			),
		Line(),
		Id(groupVar).Dot("GET").Call(Lit(baseRoute), Id(input.receiverVarName).Dot(handlerMethodName(getAllPaginatedMethodKey))),
		Id(groupVar).Dot("POST").Call(Lit(baseRoute), Id(input.receiverVarName).Dot(handlerMethodName(saveMethodKey))),
		Id(groupVar).Dot("GET").Call(Lit(byIdRoute), Id(input.receiverVarName).Dot(handlerMethodName(getByIdMethodKey))),
		Id(groupVar).Dot("PATCH").Call(Lit(byIdRoute), Id(input.receiverVarName).Dot(handlerMethodName(saveMethodKey))),
		Id(groupVar).Dot("PUT").Call(Lit(byIdRoute), Id(input.receiverVarName).Dot(handlerMethodName(updateSelectiveByIdMethodKey))),
		Id(groupVar).Dot("DELETE").Call(Lit(byIdRoute), Id(input.receiverVarName).Dot(handlerMethodName(deleteByIdMethodKey))),
	)
}

func generateControllerStruct(input usefulData) Code {
	return Null().
		Type().
		Id(input.controllerStructName).
		Struct(
			Id(input.repositoryStructVarName).Op(pointerKeyword).Id(input.repositoryStructName),
		)
}

func generateControllerConstructor(input usefulData) Code {
	return Func().
		Id(input.controllerStructConstructorName).
		Params(
			Id(input.repositoryStructVarName).Op(pointerKeyword).Id(input.repositoryStructName),
		).
		Op(pointerKeyword).Id(input.controllerStructName).
		Block(
			Return(
				Op(receiverPointerKeyword).Id(input.controllerStructName).Values(
					Dict{
						Id(input.repositoryStructVarName): Id(input.repositoryStructVarName),
					},
				),
			),
		)
}

func generateControllerSaveMethod(input usefulData) Code {
	return Func().
		Params(
			controllerReceiverParam(input),
		).
		Id(handlerMethodName(saveMethodKey)).
		Params(
			echoContextParam(),
		).
		Params(
			Error(),
		).
		Block(
			Var().Id(reqKeyword).Op("=").Add(input.modelStructQualifier).Values(),
			If(
				Err().Op(":=").Qual(winterQual, winterBindAndValidate).Call(Id(ctxKeyword), Op(receiverPointerKeyword).Id(reqKeyword)),
				Err().Op("!=").Nil(),
			).Block(
				Return(Err()),
			).Line(),
			If(
				Err().Op(":=").Id(input.receiverVarName).Dot(input.repositoryStructVarName).Dot(saveMethodKey).Call(
					Op(receiverPointerKeyword).Id(reqKeyword),
				),
				Err().Op("!=").Nil(),
			).Block(
				Return(Err()),
			),
			Line(),
			Return(
				Id(ctxKeyword).Dot("JSON").Call(Qual(netHttpQual, "StatusCreated"), Op(receiverPointerKeyword).Id(reqKeyword)),
			),
		)
}

func generateControllerGetById(input usefulData) Code {
	return Func().
		Params(
			controllerReceiverParam(input),
		).
		Id(handlerMethodName(getByIdMethodKey)).
		Params(echoContextParam()).
		Error().
		Block(
			Id(reqKeyword).Op(":=").Qual(winterCommonReqQual, ternary.If(input.isIdUUID, "GetByIdUUID", "GetById")).Values(),
			If(
				Err().Op(":=").Qual(winterQual, winterBindAndValidate).Call(Id(ctxKeyword), Op(receiverPointerKeyword).Id(reqKeyword)),
				Err().Op("!=").Nil(),
			).Block(
				Return(Err()),
			),
			Line(),
			List(Id(resKeyword), Err()).Op(":=").Id(input.receiverVarName).Dot(input.repositoryStructVarName).Dot(getByIdMethodKey).Call(
				Id(reqKeyword).Dot("Id"),
			),
			If(Err().Op("!=").Nil()).Block(
				Return(Err()),
			),
			Line(),
			Return(
				Id(ctxKeyword).Dot("JSON").Call(Qual(netHttpQual, "StatusOK"), Op(receiverPointerKeyword).Id(resKeyword)),
			),
		)
}

func generateControllerGetAllPaginatedMethods(input usefulData) Code {
	return Func().
		Params(controllerReceiverParam(input)).
		Id(handlerMethodName(getAllPaginatedMethodKey)).
		Params(echoContextParam()).
		Error().
		Block(
			Id(reqKeyword).Op(":=").Qual(winterCommonReqQual, winterRequestsPageData).Values(),
			If(
				Err().Op(":=").Qual(winterQual, winterBindAndValidate).Call(Id(ctxKeyword), Op(receiverPointerKeyword).Id(reqKeyword)),
				Err().Op("!=").Nil(),
			).Block(
				Return(Err()),
			),
			Line(),
			List(Id(resKeyword), Err()).Op(":=").Id(input.receiverVarName).Dot(input.repositoryStructVarName).Dot(getAllPaginatedMethodKey).Call(
				Id(reqKeyword).Dot("PageNumber"), Id(reqKeyword).Dot("PageSize"),
			),
			If(Err().Op("!=").Nil()).Block(
				Return(Err()),
			),
			Line(),
			Return(
				Id(ctxKeyword).Dot("JSON").Call(
					Qual(netHttpQual, "StatusOK"),
					Op(receiverPointerKeyword).Id(resKeyword),
				),
			),
		)
}

func generateControllerUpdateSelectiveMethod(input usefulData) Code {
	return Func().
		Params(controllerReceiverParam(input)).
		Id(handlerMethodName(updateSelectiveByIdMethodKey)).
		Params(echoContextParam()).
		Error().
		Block(
			Id(reqKeyword).Op(":=").Id(input.updateSelectiveByIdInputStructName).Values(),
			If(
				Err().Op(":=").Qual(winterQual, winterBindAndValidate).Call(Id(ctxKeyword), Op(receiverPointerKeyword).Id(reqKeyword)),
				Err().Op("!=").Nil(),
			).Block(
				Return(Err()),
			),
			List(Id(resKeyword), Err()).Op(":=").Id(input.receiverVarName).Dot(input.repositoryStructVarName).Dot(updateSelectiveByIdMethodKey).Call(Id(reqKeyword)),
			If(Err().Op("!=").Nil()).Block(
				Return(Err()),
			),
			Line(),
			Return(
				Id(ctxKeyword).Dot("JSON").Call(
					Qual(netHttpQual, "StatusOK"),
					Op(receiverPointerKeyword).Id(resKeyword),
				),
			),
		)
}

func generateControllerDeleteByIdMethod(input usefulData) Code {
	return Func().
		Params(controllerReceiverParam(input)).
		Id(handlerMethodName(deleteByIdMethodKey)).
		Params(echoContextParam()).
		Error().
		Block(
			Id(reqKeyword).Op(":=").Qual(winterCommonReqQual, ternary.If(input.isIdUUID, "GetByIdUUID", "GetById")).Values(),
			If(
				Err().Op(":=").Qual(winterQual, winterBindAndValidate).Call(Id(ctxKeyword), Op(receiverPointerKeyword).Id(reqKeyword)),
				Err().Op("!=").Nil(),
			).Block(
				Return(Err()),
			),
			If(
				Err().Op(":=").Id(input.receiverVarName).Dot(input.repositoryStructVarName).Dot(deleteByIdMethodKey).Call(
					Id(reqKeyword).Dot("Id"),
				),
				Err().Op("!=").Nil(),
			).Block(
				Return(Err()),
			),
			Line(),
			Return(
				Id(ctxKeyword).Dot("NoContent").Call(
					Qual(netHttpQual, "StatusOK"),
				),
			),
		)
}

func handlerMethodName(name string) string {
	return fmt.Sprintf("%sHandler", name)
}

func echoContextParam() Code {
	return Id(ctxKeyword).Qual(echoQual, "Context")
}

func controllerReceiverParam(input usefulData) Code {
	return Id(input.receiverVarName).Op(pointerKeyword).Id(input.controllerStructName)
}
