package main

import (
	. "github.com/dave/jennifer/jen"
	"os"
)

func createControllerFile(data usefulData) error {
	jf := NewFile(data.modelsKey)
	jf.ImportAlias("github.com/labstack/echo/v4", "echo")
	jf.PackageComment("Code generated by creatore")

	jf.Add(generateControllerCode(data))

	return jf.Render(os.Stdout)
}

func generateControllerCode(input usefulData) Code {
	return Null().
		Type().
		Id(input.controllerStructName).
		Struct(
			Id(input.repositoryStructVarName).Op("*").Qual(input.modelServicePackageName, input.repositoryStructName),
		).
		Line().
		Line().
		Func().
		Id(input.controllerStructConstructorName).
		Params(
			Id(input.repositoryStructVarName).Op("*").Qual(input.modelServicePackageName, input.repositoryStructName),
		).
		Op("*").Qual(input.modelServicePackageName, input.repositoryStructName).
		Block(
			Return(
				Op("&").Id(input.controllerStructName).Values(
					Dict{
						Id(input.repositoryStructVarName): Id(input.repositoryStructVarName),
					},
				),
			),
		).Line().Line().
		Func().
		Params(
			Id(input.receiverVarName).Op("*").Id(input.controllerStructName),
		).
		Id(saveMethodKey).
		Params(
			Id("ctx").Qual("github.com/labstack/echo/v4", "Context"),
		).
		Params(
			Error(),
		).
		Block(
			Var().Id("req").Op("=").Add(input.modelStructQualifier).Values(),
			If(
				Err().Op(":=").Id("ctx").Dot("Bind").Call(
					Op("&").Id("req"),
				),
				Err().Op("!=").Nil(),
			).
				Block(
					Return(Err()),
				).Line(),
			If(
				Err().Op(":=").Id("ctx").Dot("Validate").Call(
					Op("&").Id("req"),
				),
				Err().Op("!=").Nil(),
			).
				Block(
					Return(Err()),
				).Line(),
			If(
				Err().Op(":=").Id(input.receiverVarName).Dot(input.repositoryStructVarName).Dot(saveMethodKey).Call(
					Op("&").Id("req"),
				),
				Err().Op("!=").Nil(),
			).Block(
				Return(Err()),
			),
			Return(
				Id("ctx").Dot("JSON").Call(Qual("http", "StatusCreated"), Op("&").Id("req")),
			),
		)

}
