package main

import (
	jen "github.com/dave/jennifer/jen"
	"github.com/iancoleman/strcase"
	"github.com/rjNemo/underscore"
	"os"
)

const idKey = "Id"

type (
	EntityField struct {
		Name       string
		Type       string
		IsOptional bool
	}
	CreateEntityInput struct {
		EntityName string
		IsUuid     bool
		Fields     []EntityField
	}
)

func createEntityFile(input CreateEntityInput) error {
	entityNameAsCamel := strcase.ToCamel(input.EntityName)
	jf := jen.NewFile("entities")
	jf.PackageComment("Code generated by creatore")

	input.Fields = append([]EntityField{createIdField(input)}, input.Fields...)

	jf.Add(generateEntityCode(input, entityNameAsCamel))

	return jf.Render(os.Stdout)
}

func generateEntityCode(input CreateEntityInput, entityNameAsCamel string) jen.Code {
	return jen.Null().Type().Id(entityNameAsCamel).Struct(handleEntityFields(input.Fields)...)
}

func createIdField(input CreateEntityInput) EntityField {
	if input.IsUuid {
		return EntityField{
			Name: idKey,
			Type: "uuid",
		}
	}
	return EntityField{
		Name: idKey,
		Type: "int",
	}
}

func handleEntityFields(fields []EntityField) []jen.Code {
	return underscore.Map(fields, func(t EntityField) jen.Code {
		builder := jen.Null().Id(strcase.ToCamel(t.Name))

		if t.IsOptional {
			builder.Qual("github.com/manicar2093/goption", "goption").Index(getType(t.Type)).Tag(getFiledTags(t))
		} else {
			builder.Add(getType(t.Type)).Tag(getFiledTags(t))

		}
		return builder
	})
}

func getFiledTags(field EntityField) map[string]string {
	tags := make(map[string]string)
	tags["json"] = strcase.ToSnake(field.Name)
	tags["mapstructure"] = strcase.ToSnake(field.Name)
	if field.Name == idKey {
		tags["gorm"] = "default:gen_random_uuid()"
	}
	return tags
}

func getType(t string) jen.Code {
	switch t {
	case "decimal":
		return jen.Qual("github.com/quagmt/udecimal", "Decimal")
	case "uuid":
		return jen.Qual("github.com/google/uuid", "UUID")
	case "time":
		return jen.Qual("time", "Time")
	default:
		return jen.Id(t)
	}
}
