package main

import (
	. "github.com/dave/jennifer/jen"
	"github.com/rjNemo/underscore"
	"os"
)

const idKey = "Id"

type (
	EntityField struct {
		Name       string
		Type       string
		IsOptional bool
	}
	CreateEntityInput struct {
		EntityName string
		IsUuid     bool
		Fields     []EntityField
	}
)

func createEntityFile(input CreateEntityInput, data usefulData) error {
	jf := NewFile(data.entitiesKey)
	jf.PackageComment("Code generated by creatore")

	jf.Add(generateEntityCode(data))

	return jf.Render(os.Stdout)
}

func generateEntityCode(input usefulData) Code {
	return Null().Type().Id(input.entityStructName).Struct(handleEntityFields(input.fields)...)
}

func handleEntityFields(fields []fieldMeta) []Code {
	return underscore.Map(fields, func(t fieldMeta) Code {
		return t.typeAsJenCode.Tag(t.tags)
	})
}
