package main

import (
	jen "github.com/dave/jennifer/jen"
	"github.com/iancoleman/strcase"
	"github.com/rjNemo/underscore"
	"os"
)

const idKey = "Id"

type (
	EntityField struct {
		Name       string
		Type       string
		IsOptional bool
	}
	CreateEntityInput struct {
		EntityName string
		IsUuid     bool
		Fields     []EntityField
	}
)

func createEntityFile(input CreateEntityInput, data usefulData) error {
	jf := jen.NewFile(data.entitiesKey)
	jf.PackageComment("Code generated by creatore")

	input.Fields = append([]EntityField{createIdField(input)}, input.Fields...)

	jf.Add(generateEntityCode(data))

	return jf.Render(os.Stdout)
}

func generateEntityCode(input usefulData) jen.Code {
	return jen.Null().Type().Id(input.entityStructName).Struct(handleEntityFields(input.fields)...)
}

func handleEntityFields(fields []fieldMeta) []jen.Code {
	return underscore.Map(fields, func(t fieldMeta) jen.Code {
		builder := jen.Null().Id(t.nameForStructAttribute)

		if t.field.IsOptional {
			builder.Qual("github.com/manicar2093/goption", "goption").Index(t.typeAsJenCode).Tag(getFieldTags(t.field))
		} else {
			builder.Add(t.typeAsJenCode).Tag(getFieldTags(t.field))

		}
		return builder
	})
}

func getFieldTags(field EntityField) map[string]string {
	tags := make(map[string]string)
	tags["json"] = strcase.ToSnake(field.Name)
	tags["mapstructure"] = strcase.ToSnake(field.Name)
	switch {
	case field.Name == idKey && field.Type == "uuid":
		tags["gorm"] = "default:gen_random_uuid()"
	case field.Name == idKey && field.Type == "uint":
		tags["gorm"] = "primaryKey"
	}

	return tags
}
