package main

import (
	"github.com/charmbracelet/log"
	. "github.com/dave/jennifer/jen"
	"github.com/rjNemo/underscore"
)

const idKey = "Id"

type (
	ModelFieldData struct {
		Name       string
		Type       string
		IsOptional bool
	}
	ModelCreationInput struct {
		EntityName string
		IsIdUuid   bool
		Fields     []ModelFieldData
	}
)

func createModelFile(data usefulData) error {
	log.Info("Creating model code...")
	jf := NewFile(data.ModelsKey)
	jf.PackageComment("Code generated by creatore")

	jf.Add(generateModelCode(data))

	return jf.Save(data.DirNames.ModelFile)
}

func generateModelCode(input usefulData) Code {
	return Null().Type().Id(input.ModelStructName).Struct(handleModelFields(input.Fields)...)
}

func handleModelFields(fields []FieldMeta) []Code {
	return underscore.Map(fields, func(f FieldMeta) Code {
		builder := Null().Id(f.NameForStructAttribute)
		if f.Field.IsOptional {
			builder.Qual("github.com/manicar2093/goption", "goption").Index(f.TypeAsJenCode)
		} else {
			builder.Add(f.TypeAsJenCode)
		}
		return builder.Tag(f.Tags)
	})
}
