package main

import (
	"fmt"
	"github.com/charmbracelet/log"
	. "github.com/dave/jennifer/jen"
	"github.com/rjNemo/underscore"
	"log/slog"
)

const idKey = "Id"

var logger = slog.Default()

type (
	ModelFieldData struct {
		Name       string
		Type       string
		IsOptional bool
	}
	ModelCreationInput struct {
		EntityName string
		IsUuid     bool
		Fields     []ModelFieldData
	}
)

func createModelFile(data usefulData) error {
	log.Info("Creating model code...")
	jf := NewFile(data.modelsKey)
	jf.PackageComment("Code generated by creatore")

	jf.Add(generateModelCode(data))

	return jf.Save(fmt.Sprintf("./domain/models/%s_creatore.go", data.modelServicePackageName))
}

func generateModelCode(input usefulData) Code {
	return Null().Type().Id(input.modelStructName).Struct(handleModelFields(input.fields)...)
}

func handleModelFields(fields []fieldMeta) []Code {
	return underscore.Map(fields, func(f fieldMeta) Code {
		builder := Null().Id(f.nameForStructAttribute)
		if f.field.IsOptional {
			builder.Qual("github.com/manicar2093/goption", "goption").Index(f.typeAsJenCode)
		} else {
			builder.Add(f.typeAsJenCode)
		}
		return builder.Tag(f.tags)
	})
}
