package main

import (
	"fmt"
	. "github.com/dave/jennifer/jen"
	"github.com/rjNemo/underscore"

	"os"
)

const (
	createMethodKey     = "Create"
	getByIdMethodKey    = "GetById"
	getAllMethodKey     = "GetAll"
	updateMethodKey     = "Update"
	updateSomeMethodKey = "UpdateSome"
	deleteByIdMethodKey = "DeleteById"
)

type methodGenerators func(input usefulData, fnTargetKeyword *Statement) Code

var (
	RepoSupportedMethods = []string{
		createMethodKey, getByIdMethodKey, getAllMethodKey, updateMethodKey, updateSomeMethodKey, deleteByIdMethodKey,
	}
	repoMethodsGeneratorsMap = map[string]methodGenerators{
		createMethodKey: func(input usefulData, fnTargetKeyword *Statement) Code {
			return fnTargetKeyword.Id(createMethodKey).Params(
				Id("input").Op("*").Qual(fmt.Sprintf("%s/%s", input.moduleName, input.entitiesKey), input.entityStructName),
			).Error().
				Block(
					If(
						Error().Op(":=").Id("c").Dot("db").Dot("Create").Call(
							Id("input"),
						),
						Err().Op("!=").Nil(),
					).Block(
						Return(Error()),
					).Line().
						Return(
							Nil(),
						),
				).Line().Line()
		},
		getByIdMethodKey: func(input usefulData, fnTargetKeyword *Statement) Code {
			return fnTargetKeyword.Id(getByIdMethodKey).Params(
				Id("input").Id("string"),
			).Params(
				Id("string"), Error(),
			).Block(
				Comment("TODO: implement me!"),
				Id("panic").Call(Lit("implement me!")),
			).Line().Line()
		},
		getAllMethodKey: func(input usefulData, fnTargetKeyword *Statement) Code {
			return fnTargetKeyword.Id(getAllMethodKey).Params(
				Id("input").Id("string"),
			).Params(
				Id("string"), Error(),
			).Block(
				Comment("TODO: implement me!"),
				Id("panic").Call(Lit("implement me!")),
			).Line().Line()
		},
		updateMethodKey: func(input usefulData, fnTargetKeyword *Statement) Code {
			return fnTargetKeyword.Id(updateMethodKey).Params(
				Id("input").Id("string"),
			).Params(
				Id("string"), Error(),
			).Block(
				Comment("TODO: implement me!"),
				Id("panic").Call(Lit("implement me!")),
			).Line().Line()
		},
		updateSomeMethodKey: func(input usefulData, fnTargetKeyword *Statement) Code {
			return fnTargetKeyword.Id(updateSomeMethodKey).Params(
				Id("input").Id("string"),
			).Params(
				Id("string"), Error(),
			).Block(
				Comment("TODO: implement me!"),
				Id("panic").Call(Lit("implement me!")),
			).Line().Line()
		},
		deleteByIdMethodKey: func(input usefulData, fnTargetKeyword *Statement) Code {
			return fnTargetKeyword.Id(deleteByIdMethodKey).Params(
				Id("input").Id("string"),
			).Params(
				Id("string"), Error(),
			).Block(
				Comment("TODO: implement me!"),
				Id("panic").Call(Lit("implement me!")),
			).Line().Line()
		},
	}
)

func createRepositoryFile(data usefulData) error {
	jf := NewFile(data.entityServicePackageName)
	jf.PackageComment("Code generated by creatore")

	jf.Add(generateRepositoryCode(data)...)

	return jf.Render(os.Stdout)
}

func generateRepositoryCode(data usefulData) []Code {
	var result []Code
	result = append(result, Null().Type().Id(data.repositoryStructName).Struct(
		Id("db").Op("*").Qual("github.com/manicar2093/winter/connections", "connections"),
	).Line().Line())
	result = append(result, Null().Func().Id(data.repositoryStructConstructorName).Params(
		Id("db").Op("*").Qual("github.com/manicar2093/winter/connections", "connections"),
	).Block(
		Return(
			Id(fmt.Sprintf("&%s", data.repositoryStructName)).Values(
				Dict{
					Id("db"): Id("db"),
				},
			),
		),
	).Line().Line())

	underscore.Each(RepoSupportedMethods, func(s string) {
		result = append(result, repoMethodsGeneratorsMap[s](data, Func().Params(
			Id("c").Op("*").Id(data.repositoryStructName),
		).Clone()))
	})

	return result

}
