package main

import (
	"fmt"
	jen "github.com/dave/jennifer/jen"
	"github.com/gertd/go-pluralize"
	"github.com/iancoleman/strcase"
	"github.com/rjNemo/underscore"

	"os"
)

type (
	CreateRepositoryInput struct {
		CreateEntityInput
	}
)

func createRepositoryFile(input CreateRepositoryInput) error {
	pc := pluralize.NewClient()
	pluralizedRepoName := pc.Plural(input.EntityName)
	jf := jen.NewFile(strcase.ToSnake(pluralizedRepoName))
	jf.PackageComment("Code generated by creatore")

	jf.Add(generateRepositoryCode(input, strcase.ToCamel(pluralizedRepoName))...)

	return jf.Render(os.Stdout)
}

func generateRepositoryCode(input CreateRepositoryInput, pluralizedRepoName string) []jen.Code {
	repoName := fmt.Sprintf("%sRepository", pluralizedRepoName)
	jen.Null().Type().Id(repoName).Struct(
		jen.Id("db").Op("*").Qual("github.com/manicar2093/winter/connections", "connections"),
	)
	forRepo := jen.Func().Params(
		jen.Id("c").Id(fmt.Sprintf("*%s", repoName)),
	)

	return underscore.Map([]string{"Create", "GetById", "GetAll", "Update", "UpdateSome", "DeleteById"}, func(t string) jen.Code {
		return forRepo.Clone().Id(t).Params(
			jen.Id("input").Id("string"),
		).Params(
			jen.Id("string"), jen.Error(),
		).Block(
			jen.Comment("implement me!"),
			jen.Return(
				jen.Lit(""),
				jen.Nil(),
			),
		).Line().Line()
	})

}
