package main

import (
	"fmt"
	"github.com/charmbracelet/log"
	. "github.com/dave/jennifer/jen"
	"github.com/julien040/go-ternary"
	"github.com/rjNemo/underscore"
)

const (
	saveMethodKey                = "Save"
	getByIdMethodKey             = "GetById"
	getAllPaginatedMethodKey     = "GetAllPaginated"
	updateSelectiveByIdMethodKey = "UpdateSelectiveById"
	deleteByIdMethodKey          = "DeleteById"
	dbKeyword                    = "db"
)

type methodGenerators func(input usefulData, fnTargetKeyword *Statement) Code

var (
	RepoSupportedMethods = []string{
		saveMethodKey, getByIdMethodKey, getAllPaginatedMethodKey, updateSelectiveByIdMethodKey, deleteByIdMethodKey,
	}
	repoMethodsGeneratorsMap = map[string]methodGenerators{
		saveMethodKey:                saveMethodGenerator,
		getByIdMethodKey:             getByIdMethodGenerator,
		getAllPaginatedMethodKey:     getAllPaginatedMethodGenerator,
		updateSelectiveByIdMethodKey: updateSelectiveByIdMethodGenerator,
		deleteByIdMethodKey:          deleteByIdMethodGenerator,
	}
)

func createRepositoryFile(data usefulData) error {
	log.Info("Creating repository code...")
	jf := NewFile(data.ModelServicePackageName)
	jf.PackageComment("Code generated by creatore")

	jf.Add(generateRepositoryCode(data))

	return jf.Save(data.DirNames.RepositoryFile)
}

func generateRepositoryCode(input usefulData) Code {
	result := Null().
		Type().
		Id(input.RepositoryStructName).
		Struct(
			Id(dbKeyword).Op(pointerKeyword).Qual(winterConnectionsQual, winterConnectionsConnWrapperQual),
		).
		Line().
		Line().
		Func().
		Id(input.RepositoryStructConstructorName).
		Params(
			Id(dbKeyword).Op(pointerKeyword).Qual(winterConnectionsQual, winterConnectionsConnWrapperQual),
		).Op(pointerKeyword).Id(input.RepositoryStructName).Block(
		Return(
			Id(fmt.Sprintf("&%s", input.RepositoryStructName)).
				Values(
					Dict{
						Id(dbKeyword): Id(dbKeyword),
					},
				),
		),
	).Line().Line()

	underscore.Each(RepoSupportedMethods, func(s string) {
		funcContext := Func().Params(
			Id(input.ReceiverVarName).Op(pointerKeyword).Id(input.RepositoryStructName),
		)

		result.Add(repoMethodsGeneratorsMap[s](input, funcContext))
	})

	return result
}

func saveMethodGenerator(input usefulData, fnTargetKeyword *Statement) Code {
	return Commentf("%s can Create and Update an entity. You can use this for http PATH method. Check https://gorm.io/docs/update.html#Save-All-Fields for more info", saveMethodKey).
		Line().
		Add(fnTargetKeyword).Id(saveMethodKey).
		Params(
			Id("input").Op(pointerKeyword).Add(input.ModelStructQualifier),
		).Error().
		Block(
			If(
				Id("res").Op(":=").Id(input.ReceiverVarName).Dot(dbKeyword).Dot("Save").Call(
					Id("input"),
				),
				Id("res").Dot("Error").Op("!=").Nil(),
			).Block(
				Return(Id("res").Dot("Error")),
			).Line().
				Return(
					Nil(),
				),
		).Line().Line()
}

func getByIdMethodGenerator(input usefulData, fnTargetKeyword *Statement) Code {
	return fnTargetKeyword.Id(getByIdMethodKey).Params(
		Id("id").Add(input.IdTypeAsJenCode),
	).Params(
		Op(pointerKeyword).Add(input.ModelStructQualifier),
		Error(),
	).Block(
		Var().Id("found").Add(input.ModelStructQualifier),
		If(
			Id("res").Op(":=").Id(input.ReceiverVarName).Dot(dbKeyword).Dot("First").Call(
				Op(receiverPointerKeyword).Id("found"),
				Id("id"),
			),
			Id("res").Dot("Error").Op("!=").Nil(),
		).Block(
			Return(Nil(), Id("res").Dot("Error")),
		),
		Return(Op(receiverPointerKeyword).Id("found"), Nil()),
	).Line().Line()
}

func getAllPaginatedMethodGenerator(input usefulData, fnTargetKeyword *Statement) Code {
	return fnTargetKeyword.Id(getAllPaginatedMethodKey).Params(
		Id("pageNumber").Op(",").Id("pageSize").Int(),
	).Params(
		Op(pointerKeyword).Qual(gormppagerQual, gormppagerPageQual).Index(input.ModelStructQualifier),
		Error(),
	).Block(
		Id("pager").Op(":=").Qual(gormppagerQual, gormppagerPageQual).Index(input.ModelStructQualifier).Values(
			Id("PageSize").Op(":").Int64().Call(Id("pageSize")),
			Id("CurrentPage").Op(":").Int64().Call(Id("pageNumber")),
		),
		If(
			Id("err").Op(":=").Id("pager").Dot("SelectPages").Call(
				Id(input.ReceiverVarName).Dot(dbKeyword).Dot("GormPager"),
				Id(input.ReceiverVarName).Dot(dbKeyword).Dot("DB"),
			),
			Id("err").Op("!=").Nil(),
		).Block(
			Return(Nil(), Err()),
		),
		Return(Op(receiverPointerKeyword).Id("pager"), Nil()),
	).Line().Line()
}

func updateSelectiveByIdMethodGenerator(input usefulData, fnTargetKeyword *Statement) Code {
	strct := Null().Type().Id(input.UpdateSelectiveByIdInputStructName).Struct(
		underscore.Map(input.Fields, func(meta FieldMeta) Code {
			if meta.Field.Name == "Id" {
				// TODO: create a new way to generate Tags
				return Null().Id(meta.NameForStructAttribute).Add(meta.TypeAsJenCode).Tag(map[string]string{"json": "id", "param": "id", "validate": ternary.If(input.IsIdUUID, "required_uuid", "required")})
			}
			return Null().Id(meta.NameForStructAttribute).Qual(optionalQual, optionalName).Index(meta.TypeAsJenCode).Tag(meta.Tags)
		})...,
	)

	mapWithUpdateData := Id("updates").Op("=").Map(Id("string")).Id("any").Block()
	resultVar := Id("result").Op("=").Add(input.ModelStructQualifier).Block()

	varDeclarations := Var().Defs(resultVar, mapWithUpdateData)

	optionValidations := underscore.Map(input.Fields, func(meta FieldMeta) Code {
		if meta.Field.Name == "Id" {
			return nil
		}
		return If(Id("changes").Dot(meta.NameForStructAttribute).Dot("IsPresent").Call()).Block(
			Id("updates").
				Index(Lit(meta.NameForTags)).
				Op("=").
				Id("changes").
				Dot(meta.NameForStructAttribute).
				Dot("MustGet").
				Call(),
		)
	})

	updateBody := []Code{
		varDeclarations,
		Line(),
	}
	updateBody = append(updateBody, optionValidations...)
	updateGormCall := If(
		Id("res").Op(":=").Id(input.ReceiverVarName).Dot(dbKeyword).Dot("Model").Call(Id(fmt.Sprintf("&%s", "result"))).Dot("Clauses").Call(Id("clause.Returning{}")).Dot("Where").Call(Lit("id = ?"), Id("changes").Dot("Id")).Dot("Updates").Call(Id("updates")),
		Id("res").Dot("Error").Op("!=").Nil(),
	).Block(
		Return(Nil(), Id("res").Dot("Error")),
	)
	updateBody = append(updateBody,
		Line(),
		updateGormCall,
		Return(Op(receiverPointerKeyword).Id("result"), Nil()),
	)

	return strct.
		Line().
		Line().
		Commentf("%s can select which Field has to be updated from given input", updateSelectiveByIdMethodKey).
		Line().
		Add(fnTargetKeyword).
		Id(updateSelectiveByIdMethodKey).
		Params(
			Id("changes").Id(input.UpdateSelectiveByIdInputStructName),
		).Params(
		Op(pointerKeyword).Add(input.ModelStructQualifier), Error(),
	).Block(
		updateBody...,
	).Line().Line()
}

func deleteByIdMethodGenerator(input usefulData, fnTargetKeyword *Statement) Code {
	return fnTargetKeyword.Id(deleteByIdMethodKey).Params(
		Id("id").Add(input.IdTypeAsJenCode),
	).Params(
		Error(),
	).Block(
		If(
			Id("res").Op(":=").Id(input.ReceiverVarName).Dot(dbKeyword).Dot("Delete").Call(
				Op(receiverPointerKeyword).Add(input.ModelStructQualifier).Block(),
				Lit("id = ?"),
				Id("id"),
			),
			Id("res").Dot("Error").Op("!=").Nil(),
		).Block(
			Return(Id("res").Dot("Error")),
		),
		Return(Nil()),
	).Line().Line()
}
